AWSTemplateFormatVersion: '2010-09-09'
Description: Template for creating an S3 bucket, Lambda function, and SNS topic.

Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket
    Default: melhor-preco-10-raw

Resources:
  S3BucketRaw:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: BestPrice

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket
    Value: !Ref BucketName

  SNSTopicName:
    Description: Name of the SNS topic
    Value: !Ref MySNSTopic